- id: optimize-images
  name: optimize images
  description: going into folder and do a recursive image optimization
  language: golang
  types: [ file ]
  files: \.(png|jpg|jpeg|gif|svg)$
  entry: cd tools/image-optimizer && go run .
  args:
    - -dir=../../static
