- id: optimize-images
  name: optimize images
  description: going into folder and do a recursive image optimization
  language: script
  files: \.(png|jpg|jpeg)$
  entry: ./tools/optimize.sh
  args:
    - ../../static
