name: Deploy blog
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - content/**

concurrency:
  group: "build-deploy"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.117.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: danielr1996/envsubst-action@1.0.0
        name: Envsubst on template
        env:
          APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
          APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
          GITALK_OWNER: ${{ secrets.PROFILE_GITHUB }}
          GITALK_ADMIN: ${{ secrets.PROFILE_GITHUB }}
          GITALK_ID: "location.pathname"
          PROFILE_STATUS_EMOJI: ${{ secrets.PROFILE_STATUS_EMOJI }}
          PROFILE_LOCATION: ${{ secrets.PROFILE_LOCATION }}
          PROFILE_NAME: ${{ secrets.PROFILE_NAME }}
          PROFILE_GITHUB: ${{ secrets.PROFILE_GITHUB }}
          PROFILE_TELEGRAM: ${{ secrets.PROFILE_TELEGRAM }}
          RU_RU_COPYRIGHT: ${{ secrets.RU_RU_COPYRIGHT }}
          RU_RU_TITLE: ${{ secrets.RU_RU_TITLE }}
          RU_RU_DESCRIPTION: ${{ secrets.RU_RU_DESCRIPTION }}
          EN_US_COPYRIGHT: ${{ secrets.EN_US_COPYRIGHT }}
          EN_US_TITLE: ${{ secrets.EN_US_TITLE }}
          EN_US_DESCRIPTION: ${{ secrets.EN_US_DESCRIPTION }}
        with:
          input: example.hugo.yaml
          output: hugo.yaml
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  notify:
    name: Announce new post on Telegram
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: get notify message
        id: notify
        run: |
          cd tools/actions/scripts && python get-first-unpublished-announcement.py
      - name: send telegram message
        if: ${{ steps.notify.outputs.notify == '' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ steps.notify.outputs.notify }}
      - name: commit and push
        if: ${{ steps.notify.outputs.notify == '' }}
        run: |
          git config user.name GitHubActionsBot
          git config user.email github-actions@github.com
          git add tools/actions/db/announcements.json
          git commit -m "chore: update announcements.json"
          git push
            
          
