name: Publish announcement
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

concurrency:
  group: "publish-announcement"
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  notify:
    name: Announce new post on Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: get notify message
        id: notify
        run: |
          echo "::set-output name=notify::$(cd tools/actions/scripts && python get-first-unpublished-announcement.py)"
      - name: send telegram message
        if: ${{ steps.notify.outputs.notify != '' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ steps.notify.outputs.notify }}
      - name: commit and push
        if: ${{ steps.notify.outputs.notify != '' }}
        run: |
          git config user.name GitHubActionsBot
          git config user.email github-actions@github.com
          git add tools/actions/db/announcements.json
          git commit -m "chore: update announcements.json"
          git push